name: MyStats
version: '1.0-SNAPSHOT'
main: org.shakespeare.mystats.MyStats
api-version: '1.21'
authors: [Shakespeare]
description: Easy statistics!
website: github.com/ishakespearee
commands:
  mystats: